[metadata]
name = zap-trace
description = Attach to a process and trace what it's doing as a timeline
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/advice-animal/zap-trace/
author = Tim Hatch
author_email = tim@timhatch.com

[options]
packages = find:
python_requires = >=3.10
setup_requires =
    setuptools_scm >= 8
    setuptools >= 65
include_package_data = true
install_requires =
    frida >= 17,<18
    keke >= 0.3.0b1

[options.extras_require]
dev =
    checkdeps == 0.9.0
    mypy == 1.19.1
    ruff == 0.15.6
    tox == 4.50.0
    tox-uv == 1.33.4
test =
    coverage >= 6
    pytest >= 8

[options.entry_points]
console_scripts =
    zap-trace = zap_trace.__main__:_main

[check]
metadata = true
strict = true

[coverage:run]
branch = True
source = zap_trace,tests

[coverage:report]
fail_under = 80
precision = 1
show_missing = True
skip_covered = True

[mypy]
ignore_missing_imports = True

[tox:tox]
envlist = py{310,311,312,313,314}, coverage

[testenv]
deps = .[test]
commands =
    coverage run -m pytest
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage.{envname}

[testenv:coverage]
deps = coverage
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage
commands =
    coverage combine
    coverage report
depends =
    py{10,311,312,313,314}

